name: Pipeline CI/CD - Outfit Al Día

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integracion-continua:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias del Backend
        working-directory: ./backend
        run: npm install

      - name: Generar Prisma Client
        working-directory: ./backend
        run: npx prisma generate
        env:
          DATABASE_URL: "postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"

      - name: Validar Backend - Pruebas y Cobertura (Mínimo 70%)
        working-directory: ./backend
        run: npm test
        env:
          DATABASE_URL: "postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"

      - name: Instalar dependencias del Frontend
        working-directory: ./frontend
        run: npm install

      - name: Validar Frontend - Pruebas y Cobertura (Mínimo 70%)
        working-directory: ./frontend
        run: npm run test.ci

  despliegue-continuo:
    runs-on: ubuntu-latest
    needs: integracion-continua
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Despliegue
        run: echo "El código tiene la calidad requerida. Procediendo con el despliegue..."